# The JOB of a BOT is to KEEP A SYNCHRONIZED STATE BETWEEN a given URI (set) and
#  a SINGLE DIRECTORY. THE SET is EXTRA POINTS AND is to BE IMPLEMENTED FOR REA-
#  SONS OF KEEPING A RESOURCE UP-TO-DATE WITH ALTERNATIVES (FOR THE SAME CONTEN
#  T . MIRROR ALTERNATIVES . SHJOULD BE CALLED )

#
# The BOT SHALL OPERATE THUSLY:
#  * IT SHOULD keep a DATABASE (CLEAR TEXT) of HASHES for A GIVEN CONTENT
#  **  (This = Supposes a [: hashes.fetched ] directory as .Config)
#  ** In case of THE BOT detecting a HASH ALGO DISCREPANSY, A SPECIAL directory
#  ** STRUCTURE SHALL 

#
# The FIRST IMPLEMENTATION SHALL PROVIDE THE SKELETON FOR A google bot
# The SECOND WREWRITE SHALL BE FOR duckduckgo THEN YAHOO AND SO ON. COMES WITH
#  BATTERIES. I WANT YOUR JOB BIATCH ahahahaahahahahaahhahaa
#
